### ISSUE TITLE
error: Cannot read property 'startTime' of undefined

### ISSUE THREAD

**Issue by cilindrox** [pagerinc/metrics-client#51]
Some app instances are failing sporadically with the following trace:

```json
{
"data": "Cannot read property 'startTime' of undefined",
"stack": "TypeError: Cannot read property 'startTime' of undefined\n    at Object.server.events.on [as listener] (/home/node/app/node_modules/@pager/metrics-client/lib/index.js:115:64)\n    at module.exports.internals.Podium.internals.Podium.emit (/home/node/app/node_modules/@hapi/podium/lib/index.js:224:107)\n    at Request._finalize (/home/node/app/node_modules/@hapi/hapi/lib/request.js:447:27)\n    at Request._reply (/home/node/app/node_modules/@hapi/hapi/lib/request.js:391:14)\n    at process._tickCallback (internal/process/next_tick.js:68:7)",
"type": "Error",
"v":1
}
```

Had this happen to me a few times already, so we should investigate the root cause and implement a fix if possible.

**Comment by cilindrox** [comment]
from #49

**Comment by cilindrox** [comment]
Seems like a weird race cond where the metrics client depends on healthcheck requests to start reporting properly, but that path is not triggered on time.

**Comment by igorgolovanov** [comment]
Fixed in https://github.com/pagerinc/metrics-client/pull/53
